### ISSUE TITLE
Log 

### ISSUE THREAD

**Issue by LCL-Babar-Fr** [CJMustard1452/PocketCord#3]
Hello,

I do not understand I create a webhook

I copy the id https://discord.com/channels/660949208496472074/1105299602044887040

I pass the command pocketcord ServerLog https://discord.com/channels/660949208496472074/1105299602044887040
result seem ok
Command output | [PocketCord] PocketCord is now setup!

but nothing appears in the hook :(

Can you help me please
I use the last PocketMine version
thanks

**Comment by cjmustard** [comment]
The latest push should correct this
